---
language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - rbx-19mode
  - jruby-19mode
  - jruby-head
  - 1.9.2
  - 1.9.3
notifications:
  recipients:
    - jcmuller@gmail.com
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: 1.8.7
