    udp_server:
      address: 127.0.0.1
      port: 1234
    tcp_server:
      address: 127.0.0.1
      port: 2222
    tcp_client:
      host: 127.0.0.1
      port: 4567
      pass: /green
      fail: /red
      attempts: 5
    store:
      filename: /tmp/build_result.yml
    mask:
      regex: !ruby/regexp /.*master.*/
      policy: include
    verbose: false
